# Generated by Django 4.2.29 on 2026-03-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_app_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='app_access',
            field=models.CharField(choices=[('budget', '💰 Бюджет'), ('people', '👥 CRM — Люди'), ('all', '🔑 Все приложения')], default='budget', help_text='Реальный доступ. Задаётся администратором при подтверждении аккаунта.', max_length=20, verbose_name='Доступ к приложению'),
        ),
    ]
