# Generated by Django 4.2.29 on 2026-03-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_app_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='app_access',
            field=models.CharField(blank=True, choices=[('', '— Не назначен (ожидает одобрения) —'), ('budget', '💰 Бюджет'), ('people', '👥 CRM — Люди'), ('all', '🔑 Все приложения')], default='', help_text='Задаётся администратором при подтверждении аккаунта.', max_length=20, verbose_name='Доступ к приложению'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='requested_app',
            field=models.CharField(blank=True, choices=[('', '— Не назначен (ожидает одобрения) —'), ('budget', '💰 Бюджет'), ('people', '👥 CRM — Люди'), ('all', '🔑 Все приложения')], default='', help_text='Не используется при регистрации — доступ назначает администратор.', max_length=20, verbose_name='Запрошенный доступ'),
        ),
    ]
