# Generated by Django 4.2.29 on 2026-03-11 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_head', models.BooleanField(default=False, verbose_name='Глава семьи')),
                ('joined', models.DateField(blank=True, null=True, verbose_name='Дата вступления')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
            ],
            options={
                'verbose_name': 'Член семьи',
                'verbose_name_plural': 'Члены семьи',
            },
        ),
        migrations.CreateModel(
            name='FieldCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория полей',
                'verbose_name_plural': 'Категории полей',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='persondocument',
            name='person',
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'ordering': ['name'], 'verbose_name': 'Семья', 'verbose_name_plural': 'Семьи'},
        ),
        migrations.AlterModelOptions(
            name='fielddefinition',
            options={'ordering': ['category__order', 'order', 'label'], 'verbose_name': 'Поле анкеты', 'verbose_name_plural': 'Поля анкеты'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['full_name'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.AlterModelOptions(
            name='personrelationship',
            options={'verbose_name': 'Связь', 'verbose_name_plural': 'Связи'},
        ),
        migrations.AlterModelOptions(
            name='relationshiptype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тип связи', 'verbose_name_plural': 'Типы связей'},
        ),
        migrations.RenameField(
            model_name='fielddefinition',
            old_name='is_required',
            new_name='required',
        ),
        migrations.RemoveField(
            model_name='family',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='family',
            name='members',
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='choices_list',
        ),
        migrations.RemoveField(
            model_name='fielddefinition',
            name='section',
        ),
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_issued_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_issued_by',
        ),
        migrations.RemoveField(
            model_name='person',
            name='id_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='personrelationship',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='relationshiptype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='relationshiptype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='relationshiptype',
            name='is_bidirectional',
        ),
        migrations.AddField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлена'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='choices',
            field=models.TextField(blank=True, help_text='Каждый вариант на новой строке. Только для «Выбор из списка».', verbose_name='Варианты выбора'),
        ),
        migrations.AddField(
            model_name='person',
            name='full_name',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='Полное имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personrelationship',
            name='note',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='is_family',
            field=models.BooleanField(default=True, help_text='Снимите для внесемейных (сосед, попечитель...)', verbose_name='Семейная связь'),
        ),
        migrations.AddField(
            model_name='relationshiptype',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='family',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название / номер дела'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст (строка)'), ('number', 'Число'), ('date', 'Дата'), ('boolean', 'Да / Нет'), ('choice', 'Выбор из списка'), ('textarea', 'Длинный текст'), ('phone', 'Телефон'), ('email', 'Email')], default='text', max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='help_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='fielddefinition',
            name='name',
            field=models.SlugField(help_text='Латинские буквы и подчёркивания. Пример: passport_number', max_length=100, unique=True, verbose_name='Системное имя'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский'), ('O', 'Другой / не указан')], default='', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='personfieldvalue',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.fielddefinition', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='personfieldvalue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personfieldvalue',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='people.person', verbose_name='Человек'),
        ),
        migrations.AlterField(
            model_name='personrelationship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='personrelationship',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='personrelationship',
            name='to_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='people.person', verbose_name='Кому'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='relationshiptype',
            name='reverse_name',
            field=models.CharField(blank=True, help_text='Пример: "Отец" ↔ "Сын/Дочь"', max_length=100, verbose_name='Обратное название'),
        ),
        migrations.DeleteModel(
            name='FamilyMembership',
        ),
        migrations.DeleteModel(
            name='FamilyRole',
        ),
        migrations.DeleteModel(
            name='FieldSection',
        ),
        migrations.DeleteModel(
            name='PersonDocument',
        ),
        migrations.AddField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='people.family', verbose_name='Семья'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to='people.person', verbose_name='Человек'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='role',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_family': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='people.relationshiptype', verbose_name='Роль в семье'),
        ),
        migrations.AddField(
            model_name='fielddefinition',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='people.fieldcategory', verbose_name='Категория'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'person')},
        ),
    ]
